apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}-example-ingress
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  rules:
  - host: frontend.local
    http:
      paths:
      - backend:
          service:
            name: frontend-service
            port:
              number: 8088
        path: /
        pathType: Prefix
  - host: backend.local
    http:
      paths:
      - backend:
          service:
            name: backend
            port:
              number: 3000
        path: /
        pathType: Prefix
  - host: loginpage.local
    http:
      paths:
      - backend:
          service:
            name: loginpage-service
            port:
              number: 3001
        path: /
        pathType: Prefix