apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-init-sql
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
data:
  init.sql: {{ .Values.initSql.initSql | toYaml | indent 1 }}