version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: xc2mDcAANn0B12$yutz!
      POSTGRES_DB: mp
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d 

  backend:
    build: ./my-ecommerce-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres  
      DB_PORT: 5432  
      DB_USER: marketplace
      DB_PASSWORD: xc2mDcAANn0B12$yutz!
      DB_NAME: mp
      NODE_ENV: development
      JWT_SECRET: myjwtsecret
      AWS_ACCESS_KEY_ID: AKIAVVI5GORSYK3RPGWL
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: eu-central-1
      AWS_S3_BUCKET_NAME: nestjsmj
    depends_on:
      - postgres

  # For Loginpage microservice
  loginpage:
    build: 
      context: ./LoginPage
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres  
      DB_PORT: 5432  
      DB_USER: marketplace
      DB_PASSWORD: xc2mDcAANn0B12$yutz!
      DB_NAME: mp
      NODE_ENV: development
      JWT_SECRET: myjwtsecret
    depends_on:
      - postgres
  # -----------
  frontend:
    build: ./my-ecommerce-frontend
    ports:
      - "8088:80"
    volumes:
      - ./my-ecommerce-frontend/nginx.conf:/etc/nginx/nginx.conf  
    environment:
      NODE_ENV: development
      JWT_SECRET: myjwtsecret
    depends_on:
      - backend

volumes:
  pgdata:
