apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-service
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 }}