apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}-backend
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
    {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: backend
      {{- include "mychart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: PORT
          value: {{ quote .Values.backend.backend.env.port }}
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: app-config
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        image: {{ .Values.backend.backend.image.repository }}:{{ .Values.backend.backend.image.tag
          | default .Chart.AppVersion }}
        name: backend
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always