apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_USER: "bWFya2V0cGxhY2U="
  DB_PASSWORD: "eGMybURjQUFObjBCMTIkeXV0eiE="
  JWT_SECRET: "bXlqd3RzZWNyZXQ="
  SESSION_SECRET: "a3NqZGZuMzluZm1hc2Q4dWYzamZuM29qcjIzcmozZmozb2k="
  GOOGLE_CLIENT_ID: "MzU3MDc2NTE0OTYxLWluZ3Q4NHF0N2x2ZjVwOG5hZDQ5dW1sb3JvdmRqM3ZiLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t"
  GOOGLE_CLIENT_SECRET: "R09DU1BYLVlZemhBZnM0NzJZd3VYb2FoOHFCcTJ0UkhDZGk="
