backend:
  backend:
    env:
      port: "3000"
    image:
      repository: mj5248/test-vue-backend
      tag: latest
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  replicas: 1
  type: ClusterIP
kubernetesClusterDomain: cluster.local
